# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Simulations.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1200, 800)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 800))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(700, 700))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.SelectSource_label = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SelectSource_label.setFont(font)
        self.SelectSource_label.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectSource_label.setObjectName(_fromUtf8("SelectSource_label"))
        self.verticalLayout_3.addWidget(self.SelectSource_label)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.SelectSimulationOutput_Button = QtGui.QPushButton(self.frame)
        self.SelectSimulationOutput_Button.setObjectName(_fromUtf8("SelectSimulationOutput_Button"))
        self.gridLayout_5.addWidget(self.SelectSimulationOutput_Button, 0, 0, 1, 1)
        self.SelectSimulationOutput_lineEdit = QtGui.QLineEdit(self.frame)
        self.SelectSimulationOutput_lineEdit.setEnabled(False)
        self.SelectSimulationOutput_lineEdit.setObjectName(_fromUtf8("SelectSimulationOutput_lineEdit"))
        self.gridLayout_5.addWidget(self.SelectSimulationOutput_lineEdit, 0, 1, 1, 1)
        self.frame_10 = QtGui.QFrame(self.frame)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.frame_10)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.SelectSource_Button = QtGui.QPushButton(self.frame_10)
        self.SelectSource_Button.setObjectName(_fromUtf8("SelectSource_Button"))
        self.verticalLayout_11.addWidget(self.SelectSource_Button)
        self.RemoveSource_pushButton = QtGui.QPushButton(self.frame_10)
        self.RemoveSource_pushButton.setObjectName(_fromUtf8("RemoveSource_pushButton"))
        self.verticalLayout_11.addWidget(self.RemoveSource_pushButton)
        self.gridLayout_5.addWidget(self.frame_10, 2, 0, 1, 1)
        self.SourcesList_listWidget = QtGui.QTableWidget(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SourcesList_listWidget.sizePolicy().hasHeightForWidth())
        self.SourcesList_listWidget.setSizePolicy(sizePolicy)
        self.SourcesList_listWidget.setMaximumSize(QtCore.QSize(802, 16777215))
        self.SourcesList_listWidget.setAutoFillBackground(False)
        self.SourcesList_listWidget.setAlternatingRowColors(True)
        self.SourcesList_listWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.SourcesList_listWidget.setObjectName(_fromUtf8("SourcesList_listWidget"))
        self.SourcesList_listWidget.setColumnCount(4)
        self.SourcesList_listWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.SourcesList_listWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.SourcesList_listWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.SourcesList_listWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.SourcesList_listWidget.setHorizontalHeaderItem(3, item)
        self.SourcesList_listWidget.horizontalHeader().setVisible(True)
        self.SourcesList_listWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.SourcesList_listWidget.horizontalHeader().setDefaultSectionSize(200)
        self.SourcesList_listWidget.horizontalHeader().setMinimumSectionSize(50)
        self.SourcesList_listWidget.horizontalHeader().setSortIndicatorShown(False)
        self.SourcesList_listWidget.horizontalHeader().setStretchLastSection(False)
        self.SourcesList_listWidget.verticalHeader().setVisible(False)
        self.SourcesList_listWidget.verticalHeader().setCascadingSectionResizes(True)
        self.SourcesList_listWidget.verticalHeader().setDefaultSectionSize(30)
        self.SourcesList_listWidget.verticalHeader().setMinimumSectionSize(23)
        self.SourcesList_listWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_5.addWidget(self.SourcesList_listWidget, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_9.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.tab)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_4 = QtGui.QGroupBox(self.frame_2)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frame_6 = QtGui.QFrame(self.groupBox_4)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.formLayout = QtGui.QFormLayout(self.frame_6)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.TopAng_label = QtGui.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.TopAng_label.setFont(font)
        self.TopAng_label.setObjectName(_fromUtf8("TopAng_label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.TopAng_label)
        self.TopAng_comboBox = QtGui.QComboBox(self.frame_6)
        self.TopAng_comboBox.setMinimumSize(QtCore.QSize(0, 25))
        self.TopAng_comboBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.TopAng_comboBox.setObjectName(_fromUtf8("TopAng_comboBox"))
        self.TopAng_comboBox.addItem(_fromUtf8(""))
        self.TopAng_comboBox.addItem(_fromUtf8(""))
        self.TopAng_comboBox.addItem(_fromUtf8(""))
        self.TopAng_comboBox.addItem(_fromUtf8(""))
        self.TopAng_comboBox.addItem(_fromUtf8(""))
        self.TopAng_comboBox.addItem(_fromUtf8(""))
        self.TopAng_comboBox.addItem(_fromUtf8(""))
        self.TopAng_comboBox.addItem(_fromUtf8(""))
        self.TopAng_comboBox.addItem(_fromUtf8(""))
        self.TopAng_comboBox.addItem(_fromUtf8(""))
        self.TopAng_comboBox.addItem(_fromUtf8(""))
        self.TopAng_comboBox.addItem(_fromUtf8(""))
        self.TopAng_comboBox.addItem(_fromUtf8(""))
        self.TopAng_comboBox.addItem(_fromUtf8(""))
        self.TopAng_comboBox.addItem(_fromUtf8(""))
        self.TopAng_comboBox.addItem(_fromUtf8(""))
        self.TopAng_comboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.TopAng_comboBox)
        self.TopRange_label = QtGui.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.TopRange_label.setFont(font)
        self.TopRange_label.setObjectName(_fromUtf8("TopRange_label"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.TopRange_label)
        self.TopRange_comboBox = QtGui.QComboBox(self.frame_6)
        self.TopRange_comboBox.setMinimumSize(QtCore.QSize(0, 25))
        self.TopRange_comboBox.setObjectName(_fromUtf8("TopRange_comboBox"))
        self.TopRange_comboBox.addItem(_fromUtf8(""))
        self.TopRange_comboBox.addItem(_fromUtf8(""))
        self.TopRange_comboBox.addItem(_fromUtf8(""))
        self.TopRange_comboBox.addItem(_fromUtf8(""))
        self.TopRange_comboBox.addItem(_fromUtf8(""))
        self.TopRange_comboBox.addItem(_fromUtf8(""))
        self.TopRange_comboBox.addItem(_fromUtf8(""))
        self.TopRange_comboBox.addItem(_fromUtf8(""))
        self.TopRange_comboBox.addItem(_fromUtf8(""))
        self.TopRange_comboBox.addItem(_fromUtf8(""))
        self.TopRange_comboBox.addItem(_fromUtf8(""))
        self.TopRange_comboBox.addItem(_fromUtf8(""))
        self.TopRange_comboBox.addItem(_fromUtf8(""))
        self.TopRange_comboBox.addItem(_fromUtf8(""))
        self.TopRange_comboBox.addItem(_fromUtf8(""))
        self.TopRange_comboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.TopRange_comboBox)
        self.BotAng_label = QtGui.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.BotAng_label.setFont(font)
        self.BotAng_label.setObjectName(_fromUtf8("BotAng_label"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.BotAng_label)
        self.BotAng_comboBox = QtGui.QComboBox(self.frame_6)
        self.BotAng_comboBox.setMinimumSize(QtCore.QSize(0, 25))
        self.BotAng_comboBox.setObjectName(_fromUtf8("BotAng_comboBox"))
        self.BotAng_comboBox.addItem(_fromUtf8(""))
        self.BotAng_comboBox.addItem(_fromUtf8(""))
        self.BotAng_comboBox.addItem(_fromUtf8(""))
        self.BotAng_comboBox.addItem(_fromUtf8(""))
        self.BotAng_comboBox.addItem(_fromUtf8(""))
        self.BotAng_comboBox.addItem(_fromUtf8(""))
        self.BotAng_comboBox.addItem(_fromUtf8(""))
        self.BotAng_comboBox.addItem(_fromUtf8(""))
        self.BotAng_comboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.BotAng_comboBox)
        self.TimeLor_label = QtGui.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.TimeLor_label.setFont(font)
        self.TimeLor_label.setObjectName(_fromUtf8("TimeLor_label"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.TimeLor_label)
        self.TimeLor_doubleSpinBox = QtGui.QDoubleSpinBox(self.frame_6)
        self.TimeLor_doubleSpinBox.setMinimumSize(QtCore.QSize(0, 25))
        self.TimeLor_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.TimeLor_doubleSpinBox.setDecimals(0)
        self.TimeLor_doubleSpinBox.setMinimum(1.0)
        self.TimeLor_doubleSpinBox.setMaximum(1000.0)
        self.TimeLor_doubleSpinBox.setSingleStep(1.0)
        self.TimeLor_doubleSpinBox.setProperty("value", 25.0)
        self.TimeLor_doubleSpinBox.setObjectName(_fromUtf8("TimeLor_doubleSpinBox"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.TimeLor_doubleSpinBox)
        self.NumberOfTurns_label = QtGui.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.NumberOfTurns_label.setFont(font)
        self.NumberOfTurns_label.setObjectName(_fromUtf8("NumberOfTurns_label"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.NumberOfTurns_label)
        self.NumberOfTurns_spinBox = QtGui.QSpinBox(self.frame_6)
        self.NumberOfTurns_spinBox.setMinimumSize(QtCore.QSize(0, 25))
        self.NumberOfTurns_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.NumberOfTurns_spinBox.setMinimum(1)
        self.NumberOfTurns_spinBox.setMaximum(10)
        self.NumberOfTurns_spinBox.setProperty("value", 1)
        self.NumberOfTurns_spinBox.setObjectName(_fromUtf8("NumberOfTurns_spinBox"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.NumberOfTurns_spinBox)
        self.gridLayout_3.addWidget(self.frame_6, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_2 = QtGui.QGroupBox(self.frame_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.RunningSimulation_tableWidget = QtGui.QTableWidget(self.groupBox_2)
        self.RunningSimulation_tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.RunningSimulation_tableWidget.setObjectName(_fromUtf8("RunningSimulation_tableWidget"))
        self.RunningSimulation_tableWidget.setColumnCount(2)
        self.RunningSimulation_tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.RunningSimulation_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.RunningSimulation_tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.RunningSimulation_tableWidget)
        self.abortSimulation_Button = QtGui.QPushButton(self.groupBox_2)
        self.abortSimulation_Button.setEnabled(False)
        self.abortSimulation_Button.setObjectName(_fromUtf8("abortSimulation_Button"))
        self.verticalLayout.addWidget(self.abortSimulation_Button)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_9.addWidget(self.frame_2)
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.Simulationname_lineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.Simulationname_lineEdit.setEnabled(False)
        self.Simulationname_lineEdit.setObjectName(_fromUtf8("Simulationname_lineEdit"))
        self.gridLayout_2.addWidget(self.Simulationname_lineEdit, 0, 1, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.groupBox_3)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setFormat(_fromUtf8(""))
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_2.addWidget(self.progressBar, 1, 1, 1, 1)
        self.StartSimulation_pushButton = QtGui.QPushButton(self.groupBox_3)
        self.StartSimulation_pushButton.setEnabled(False)
        self.StartSimulation_pushButton.setCheckable(False)
        self.StartSimulation_pushButton.setAutoDefault(False)
        self.StartSimulation_pushButton.setDefault(False)
        self.StartSimulation_pushButton.setFlat(False)
        self.StartSimulation_pushButton.setObjectName(_fromUtf8("StartSimulation_pushButton"))
        self.gridLayout_2.addWidget(self.StartSimulation_pushButton, 0, 0, 2, 1)
        self.verticalLayout_9.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_7.setMaximumSize(QtCore.QSize(400, 16777215))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.Energywidget_3 = QtGui.QWidget(self.groupBox_7)
        self.Energywidget_3.setMinimumSize(QtCore.QSize(150, 100))
        self.Energywidget_3.setObjectName(_fromUtf8("Energywidget_3"))
        self.horizontalLayout_4.addWidget(self.Energywidget_3)
        self.gridLayout_8.addWidget(self.groupBox_7, 2, 1, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.SelectResults_Button = QtGui.QPushButton(self.groupBox_5)
        self.SelectResults_Button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.SelectResults_Button.setObjectName(_fromUtf8("SelectResults_Button"))
        self.horizontalLayout_6.addWidget(self.SelectResults_Button)
        self.SelectResults_lineEdit = QtGui.QLineEdit(self.groupBox_5)
        self.SelectResults_lineEdit.setEnabled(False)
        self.SelectResults_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.SelectResults_lineEdit.setObjectName(_fromUtf8("SelectResults_lineEdit"))
        self.horizontalLayout_6.addWidget(self.SelectResults_lineEdit)
        self.gridLayout_8.addWidget(self.groupBox_5, 0, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.FBPWidget = QtGui.QWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FBPWidget.sizePolicy().hasHeightForWidth())
        self.FBPWidget.setSizePolicy(sizePolicy)
        self.FBPWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.FBPWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.FBPWidget.setObjectName(_fromUtf8("FBPWidget"))
        self.verticalLayout_2.addWidget(self.FBPWidget)
        self.gridLayout_8.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.frame_4 = QtGui.QFrame(self.groupBox_6)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.pixelSize_comboBox = QtGui.QComboBox(self.frame_4)
        self.pixelSize_comboBox.setObjectName(_fromUtf8("pixelSize_comboBox"))
        self.pixelSize_comboBox.addItem(_fromUtf8(""))
        self.pixelSize_comboBox.addItem(_fromUtf8(""))
        self.pixelSize_comboBox.addItem(_fromUtf8(""))
        self.pixelSize_comboBox.addItem(_fromUtf8(""))
        self.pixelSize_comboBox.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.pixelSize_comboBox, 3, 3, 1, 1)
        self.saveFigures_pushButton = QtGui.QPushButton(self.frame_4)
        self.saveFigures_pushButton.setEnabled(False)
        self.saveFigures_pushButton.setObjectName(_fromUtf8("saveFigures_pushButton"))
        self.gridLayout_9.addWidget(self.saveFigures_pushButton, 3, 0, 1, 1)
        self.interp_comboBox = QtGui.QComboBox(self.frame_4)
        self.interp_comboBox.setObjectName(_fromUtf8("interp_comboBox"))
        self.interp_comboBox.addItem(_fromUtf8(""))
        self.interp_comboBox.addItem(_fromUtf8(""))
        self.interp_comboBox.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.interp_comboBox, 3, 2, 1, 1)
        self.gaussFilter_doubleSpinBox = QtGui.QDoubleSpinBox(self.frame_4)
        self.gaussFilter_doubleSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.gaussFilter_doubleSpinBox.setMaximum(10.0)
        self.gaussFilter_doubleSpinBox.setSingleStep(0.1)
        self.gaussFilter_doubleSpinBox.setObjectName(_fromUtf8("gaussFilter_doubleSpinBox"))
        self.gridLayout_9.addWidget(self.gaussFilter_doubleSpinBox, 3, 4, 1, 1)
        self.StartAnalysis_pushButton = QtGui.QPushButton(self.frame_4)
        self.StartAnalysis_pushButton.setEnabled(False)
        self.StartAnalysis_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.StartAnalysis_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.StartAnalysis_pushButton.setObjectName(_fromUtf8("StartAnalysis_pushButton"))
        self.gridLayout_9.addWidget(self.StartAnalysis_pushButton, 0, 0, 1, 1)
        self.filter_comboBox = QtGui.QComboBox(self.frame_4)
        self.filter_comboBox.setMinimumSize(QtCore.QSize(0, 25))
        self.filter_comboBox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.filter_comboBox.setObjectName(_fromUtf8("filter_comboBox"))
        self.filter_comboBox.addItem(_fromUtf8(""))
        self.filter_comboBox.addItem(_fromUtf8(""))
        self.filter_comboBox.addItem(_fromUtf8(""))
        self.filter_comboBox.addItem(_fromUtf8(""))
        self.filter_comboBox.addItem(_fromUtf8(""))
        self.filter_comboBox.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.filter_comboBox, 3, 1, 1, 1)
        self.Recon_pushButton = QtGui.QPushButton(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Recon_pushButton.sizePolicy().hasHeightForWidth())
        self.Recon_pushButton.setSizePolicy(sizePolicy)
        self.Recon_pushButton.setMinimumSize(QtCore.QSize(120, 30))
        self.Recon_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Recon_pushButton.setAutoDefault(False)
        self.Recon_pushButton.setDefault(False)
        self.Recon_pushButton.setFlat(False)
        self.Recon_pushButton.setObjectName(_fromUtf8("Recon_pushButton"))
        self.gridLayout_9.addWidget(self.Recon_pushButton, 1, 0, 1, 1)
        self.cmapname_comboBox = QtGui.QComboBox(self.frame_4)
        self.cmapname_comboBox.setObjectName(_fromUtf8("cmapname_comboBox"))
        self.cmapname_comboBox.addItem(_fromUtf8(""))
        self.cmapname_comboBox.addItem(_fromUtf8(""))
        self.cmapname_comboBox.addItem(_fromUtf8(""))
        self.cmapname_comboBox.addItem(_fromUtf8(""))
        self.cmapname_comboBox.addItem(_fromUtf8(""))
        self.cmapname_comboBox.addItem(_fromUtf8(""))
        self.cmapname_comboBox.addItem(_fromUtf8(""))
        self.cmapname_comboBox.addItem(_fromUtf8(""))
        self.cmapname_comboBox.addItem(_fromUtf8(""))
        self.cmapname_comboBox.addItem(_fromUtf8(""))
        self.cmapname_comboBox.addItem(_fromUtf8(""))
        self.cmapname_comboBox.addItem(_fromUtf8(""))
        self.cmapname_comboBox.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.cmapname_comboBox, 3, 5, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame_4)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_9.addWidget(self.label_4, 0, 3, 2, 1)
        self.label_3 = QtGui.QLabel(self.frame_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_9.addWidget(self.label_3, 0, 4, 2, 1)
        self.label_5 = QtGui.QLabel(self.frame_4)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_9.addWidget(self.label_5, 0, 5, 2, 1)
        self.label_2 = QtGui.QLabel(self.frame_4)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_9.addWidget(self.label_2, 0, 1, 2, 1)
        self.label = QtGui.QLabel(self.frame_4)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_9.addWidget(self.label, 0, 2, 2, 1)
        self.Recon_pushButton.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.saveFigures_pushButton.raise_()
        self.filter_comboBox.raise_()
        self.interp_comboBox.raise_()
        self.pixelSize_comboBox.raise_()
        self.gaussFilter_doubleSpinBox.raise_()
        self.cmapname_comboBox.raise_()
        self.StartAnalysis_pushButton.raise_()
        self.horizontalLayout_5.addWidget(self.frame_4)
        self.frame_3 = QtGui.QFrame(self.groupBox_6)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_6 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_7.addWidget(self.label_6, 0, 1, 1, 3)
        self.CoincidenceWindow_doubleSpinBox = QtGui.QDoubleSpinBox(self.frame_3)
        self.CoincidenceWindow_doubleSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.CoincidenceWindow_doubleSpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.CoincidenceWindow_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.CoincidenceWindow_doubleSpinBox.setDecimals(3)
        self.CoincidenceWindow_doubleSpinBox.setMaximum(999999999.0)
        self.CoincidenceWindow_doubleSpinBox.setSingleStep(0.1)
        self.CoincidenceWindow_doubleSpinBox.setProperty("value", 0.1)
        self.CoincidenceWindow_doubleSpinBox.setObjectName(_fromUtf8("CoincidenceWindow_doubleSpinBox"))
        self.gridLayout_7.addWidget(self.CoincidenceWindow_doubleSpinBox, 1, 0, 1, 1)
        self.TopAng_label_2 = QtGui.QLabel(self.frame_3)
        self.TopAng_label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.TopAng_label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.TopAng_label_2.setFont(font)
        self.TopAng_label_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.TopAng_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.TopAng_label_2.setObjectName(_fromUtf8("TopAng_label_2"))
        self.gridLayout_7.addWidget(self.TopAng_label_2, 0, 0, 1, 1)
        self.energy_threshold_upper_doubleSpinBox = QtGui.QDoubleSpinBox(self.frame_3)
        self.energy_threshold_upper_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.energy_threshold_upper_doubleSpinBox.setDecimals(0)
        self.energy_threshold_upper_doubleSpinBox.setMaximum(1499.0)
        self.energy_threshold_upper_doubleSpinBox.setProperty("value", 1499.0)
        self.energy_threshold_upper_doubleSpinBox.setObjectName(_fromUtf8("energy_threshold_upper_doubleSpinBox"))
        self.gridLayout_7.addWidget(self.energy_threshold_upper_doubleSpinBox, 1, 3, 1, 1)
        self.energy_threshold_lower_doubleSpinBox = QtGui.QDoubleSpinBox(self.frame_3)
        self.energy_threshold_lower_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.energy_threshold_lower_doubleSpinBox.setDecimals(0)
        self.energy_threshold_lower_doubleSpinBox.setMaximum(1999.0)
        self.energy_threshold_lower_doubleSpinBox.setObjectName(_fromUtf8("energy_threshold_lower_doubleSpinBox"))
        self.gridLayout_7.addWidget(self.energy_threshold_lower_doubleSpinBox, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_7.addWidget(self.label_7, 1, 2, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_3)
        self.gridLayout_8.addWidget(self.groupBox_6, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.TopAng_comboBox.setCurrentIndex(2)
        self.pixelSize_comboBox.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.SelectSource_label.setText(_translate("MainWindow", "Directory of the source file", None))
        self.SelectSimulationOutput_Button.setText(_translate("MainWindow", "Select Simulation Output", None))
        self.SelectSimulationOutput_lineEdit.setText(_translate("MainWindow", "Simulation path directory not selected", None))
        self.SelectSource_Button.setText(_translate("MainWindow", "Select source file", None))
        self.RemoveSource_pushButton.setText(_translate("MainWindow", "Remove File", None))
        item = self.SourcesList_listWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Source name and position [mm]", None))
        item = self.SourcesList_listWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "X", None))
        item = self.SourcesList_listWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Y", None))
        item = self.SourcesList_listWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Z", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Parameters", None))
        self.TopAng_label.setText(_translate("MainWindow", "Step Top (º)", None))
        self.TopAng_comboBox.setItemText(0, _translate("MainWindow", "0.225", None))
        self.TopAng_comboBox.setItemText(1, _translate("MainWindow", "0.45", None))
        self.TopAng_comboBox.setItemText(2, _translate("MainWindow", "0.9", None))
        self.TopAng_comboBox.setItemText(3, _translate("MainWindow", "1.8", None))
        self.TopAng_comboBox.setItemText(4, _translate("MainWindow", "3.6", None))
        self.TopAng_comboBox.setItemText(5, _translate("MainWindow", "7.2", None))
        self.TopAng_comboBox.setItemText(6, _translate("MainWindow", "9", None))
        self.TopAng_comboBox.setItemText(7, _translate("MainWindow", "14.4", None))
        self.TopAng_comboBox.setItemText(8, _translate("MainWindow", "18", None))
        self.TopAng_comboBox.setItemText(9, _translate("MainWindow", "27", None))
        self.TopAng_comboBox.setItemText(10, _translate("MainWindow", "36", None))
        self.TopAng_comboBox.setItemText(11, _translate("MainWindow", "45", None))
        self.TopAng_comboBox.setItemText(12, _translate("MainWindow", "54", None))
        self.TopAng_comboBox.setItemText(13, _translate("MainWindow", "63", None))
        self.TopAng_comboBox.setItemText(14, _translate("MainWindow", "72", None))
        self.TopAng_comboBox.setItemText(15, _translate("MainWindow", "81", None))
        self.TopAng_comboBox.setItemText(16, _translate("MainWindow", "90", None))
        self.TopRange_label.setText(_translate("MainWindow", "Top scan range (º)", None))
        self.TopRange_comboBox.setProperty("currentText", _translate("MainWindow", "0.9", None))
        self.TopRange_comboBox.setItemText(0, _translate("MainWindow", "0.9", None))
        self.TopRange_comboBox.setItemText(1, _translate("MainWindow", "1.8", None))
        self.TopRange_comboBox.setItemText(2, _translate("MainWindow", "3.6", None))
        self.TopRange_comboBox.setItemText(3, _translate("MainWindow", "7.2", None))
        self.TopRange_comboBox.setItemText(4, _translate("MainWindow", "9", None))
        self.TopRange_comboBox.setItemText(5, _translate("MainWindow", "14.4", None))
        self.TopRange_comboBox.setItemText(6, _translate("MainWindow", "18", None))
        self.TopRange_comboBox.setItemText(7, _translate("MainWindow", "27", None))
        self.TopRange_comboBox.setItemText(8, _translate("MainWindow", "36", None))
        self.TopRange_comboBox.setItemText(9, _translate("MainWindow", "45", None))
        self.TopRange_comboBox.setItemText(10, _translate("MainWindow", "54", None))
        self.TopRange_comboBox.setItemText(11, _translate("MainWindow", "63", None))
        self.TopRange_comboBox.setItemText(12, _translate("MainWindow", "72", None))
        self.TopRange_comboBox.setItemText(13, _translate("MainWindow", "75.6", None))
        self.TopRange_comboBox.setItemText(14, _translate("MainWindow", "81", None))
        self.TopRange_comboBox.setItemText(15, _translate("MainWindow", "90", None))
        self.BotAng_label.setText(_translate("MainWindow", "Step bottom (º)", None))
        self.BotAng_comboBox.setItemText(0, _translate("MainWindow", "0.9", None))
        self.BotAng_comboBox.setItemText(1, _translate("MainWindow", "1.8", None))
        self.BotAng_comboBox.setItemText(2, _translate("MainWindow", "3.6", None))
        self.BotAng_comboBox.setItemText(3, _translate("MainWindow", "9", None))
        self.BotAng_comboBox.setItemText(4, _translate("MainWindow", "18", None))
        self.BotAng_comboBox.setItemText(5, _translate("MainWindow", "36", None))
        self.BotAng_comboBox.setItemText(6, _translate("MainWindow", "45", None))
        self.BotAng_comboBox.setItemText(7, _translate("MainWindow", "90", None))
        self.BotAng_comboBox.setItemText(8, _translate("MainWindow", "180", None))
        self.TimeLor_label.setText(_translate("MainWindow", "Time per LOR (ms)", None))
        self.NumberOfTurns_label.setText(_translate("MainWindow", "Number of turns", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Running Simulations:", None))
        item = self.RunningSimulation_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Simulation Path", None))
        item = self.RunningSimulation_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "% Complete", None))
        self.abortSimulation_Button.setText(_translate("MainWindow", "Cancel selected simulation", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Simulation Name", None))
        self.StartSimulation_pushButton.setText(_translate("MainWindow", "Start Simulation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Simulation", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Energy Spectrum", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Simulation directory", None))
        self.SelectResults_Button.setText(_translate("MainWindow", "Select results file", None))
        self.SelectResults_lineEdit.setText(_translate("MainWindow", "Simulation results directory not selected ", None))
        self.groupBox.setTitle(_translate("MainWindow", "Image Reconstruction", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Parameters", None))
        self.pixelSize_comboBox.setItemText(0, _translate("MainWindow", "0.1", None))
        self.pixelSize_comboBox.setItemText(1, _translate("MainWindow", "0.25", None))
        self.pixelSize_comboBox.setItemText(2, _translate("MainWindow", "0.5", None))
        self.pixelSize_comboBox.setItemText(3, _translate("MainWindow", "1", None))
        self.pixelSize_comboBox.setItemText(4, _translate("MainWindow", "2", None))
        self.saveFigures_pushButton.setText(_translate("MainWindow", "Save Figures", None))
        self.interp_comboBox.setItemText(0, _translate("MainWindow", "linear", None))
        self.interp_comboBox.setItemText(1, _translate("MainWindow", "nearest", None))
        self.interp_comboBox.setItemText(2, _translate("MainWindow", "cubic", None))
        self.StartAnalysis_pushButton.setText(_translate("MainWindow", "Start Analysis", None))
        self.filter_comboBox.setItemText(0, _translate("MainWindow", "None", None))
        self.filter_comboBox.setItemText(1, _translate("MainWindow", "ramp", None))
        self.filter_comboBox.setItemText(2, _translate("MainWindow", "shepp-logan", None))
        self.filter_comboBox.setItemText(3, _translate("MainWindow", "cosine", None))
        self.filter_comboBox.setItemText(4, _translate("MainWindow", "hamming", None))
        self.filter_comboBox.setItemText(5, _translate("MainWindow", "hann", None))
        self.Recon_pushButton.setText(_translate("MainWindow", "Load Sinogram", None))
        self.cmapname_comboBox.setItemText(0, _translate("MainWindow", "hot", None))
        self.cmapname_comboBox.setItemText(1, _translate("MainWindow", "hot_r", None))
        self.cmapname_comboBox.setItemText(2, _translate("MainWindow", "Greys", None))
        self.cmapname_comboBox.setItemText(3, _translate("MainWindow", "winter", None))
        self.cmapname_comboBox.setItemText(4, _translate("MainWindow", "bone", None))
        self.cmapname_comboBox.setItemText(5, _translate("MainWindow", "hsv", None))
        self.cmapname_comboBox.setItemText(6, _translate("MainWindow", "jet", None))
        self.cmapname_comboBox.setItemText(7, _translate("MainWindow", "Reds", None))
        self.cmapname_comboBox.setItemText(8, _translate("MainWindow", "Set1", None))
        self.cmapname_comboBox.setItemText(9, _translate("MainWindow", "gnuplot", None))
        self.cmapname_comboBox.setItemText(10, _translate("MainWindow", "gnuplot2", None))
        self.cmapname_comboBox.setItemText(11, _translate("MainWindow", "rainbow", None))
        self.cmapname_comboBox.setItemText(12, _translate("MainWindow", "gist_rainbow", None))
        self.label_4.setText(_translate("MainWindow", "Pixel size (mm)", None))
        self.label_3.setText(_translate("MainWindow", "Gauss filter", None))
        self.label_5.setText(_translate("MainWindow", "Colormap", None))
        self.label_2.setText(_translate("MainWindow", "Filter type", None))
        self.label.setText(_translate("MainWindow", "Interpolation", None))
        self.label_6.setText(_translate("MainWindow", "Energy window (keV)", None))
        self.TopAng_label_2.setText(_translate("MainWindow", "Coincidence window (ns)", None))
        self.label_7.setText(_translate("MainWindow", "to", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Data analysis", None))

